// <auto-generated />
using System;
using CulinaryPairing.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CulinaryPairing.DAL.Migrations
{
    [DbContext(typeof(CulinaryPairingDbContext))]
    [Migration("20260424061121_AddMissingCheckConstraints")]
    partial class AddMissingCheckConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Accord", b =>
                {
                    b.Property<int>("IdAccord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_accord");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccord"));

                    b.Property<int>("IdBoisson")
                        .HasColumnType("int")
                        .HasColumnName("id_boisson");

                    b.Property<int>("IdRecette")
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justification");

                    b.Property<int?>("MalusApplique")
                        .HasColumnType("int")
                        .HasColumnName("malus_applique");

                    b.Property<int?>("NiveauConfiance")
                        .HasColumnType("int")
                        .HasColumnName("niveau_confiance");

                    b.Property<string>("ReglesSatisfaites")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("regles_satisfaites");

                    b.Property<int?>("ScoreCompatibilite")
                        .HasColumnType("int")
                        .HasColumnName("score_compatibilite");

                    b.Property<string>("TypeAccord")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("type_accord");

                    b.HasKey("IdAccord");

                    b.HasIndex("IdBoisson");

                    b.HasIndex("IdRecette");

                    b.ToTable("ACCORD");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Boisson", b =>
                {
                    b.Property<int>("IdBoisson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_boisson");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoisson"));

                    b.Property<bool>("Alcoolise")
                        .HasColumnType("bit")
                        .HasColumnName("alcoolise");

                    b.Property<string>("Corps")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("corps");

                    b.Property<decimal?>("CoutMoyen")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cout_moyen");

                    b.Property<decimal?>("DegreAlcool")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("degre_alcool");

                    b.Property<int?>("IntensiteAromatique")
                        .HasColumnType("int")
                        .HasColumnName("intensite_aromatique");

                    b.Property<int?>("NiveauAcidite")
                        .HasColumnType("int")
                        .HasColumnName("niveau_acidite");

                    b.Property<int?>("NiveauAmertume")
                        .HasColumnType("int")
                        .HasColumnName("niveau_amertume");

                    b.Property<int?>("NiveauFume")
                        .HasColumnType("int")
                        .HasColumnName("niveau_fume");

                    b.Property<int?>("NiveauSucre")
                        .HasColumnType("int")
                        .HasColumnName("niveau_sucre");

                    b.Property<int?>("NiveauTannins")
                        .HasColumnType("int")
                        .HasColumnName("niveau_tannins");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<int?>("TemperatureOptimale")
                        .HasColumnType("int")
                        .HasColumnName("temperature_optimale");

                    b.Property<int>("ToleranceTemperature")
                        .HasColumnType("int")
                        .HasColumnName("tolerance_temperature");

                    b.Property<string>("TypeBoisson")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_boisson");

                    b.HasKey("IdBoisson");

                    b.ToTable("BOISSON");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.BoissonFamilleAromatique", b =>
                {
                    b.Property<int>("IdBoisson")
                        .HasColumnType("int")
                        .HasColumnName("id_boisson");

                    b.Property<int>("IdFamille")
                        .HasColumnType("int")
                        .HasColumnName("id_famille");

                    b.HasKey("IdBoisson", "IdFamille");

                    b.HasIndex("IdFamille");

                    b.ToTable("BOISSON_FAMILLE_AROMATIQUE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.ContrainteAlimentaire", b =>
                {
                    b.Property<int>("IdContrainte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contrainte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrainte"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("IdContrainte");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("CONTRAINTE_ALIMENTAIRE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Etape", b =>
                {
                    b.Property<int>("IdEtape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etape");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtape"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdRecette")
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    b.Property<int>("NumeroEtape")
                        .HasColumnType("int")
                        .HasColumnName("numero_etape");

                    b.HasKey("IdEtape");

                    b.HasIndex("IdRecette", "NumeroEtape")
                        .IsUnique();

                    b.ToTable("ETAPE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.FamilleAromatique", b =>
                {
                    b.Property<int>("IdFamille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_famille");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamille"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom");

                    b.HasKey("IdFamille");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("FAMILLE_AROMATIQUE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Favori", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("IdRecette")
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_ajout");

                    b.HasKey("IdUtilisateur", "IdRecette");

                    b.HasIndex("IdRecette");

                    b.ToTable("FAVORI");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.HistoriqueConsultation", b =>
                {
                    b.Property<int>("IdHistorique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historique");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorique"));

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_consultation");

                    b.Property<int>("IdRecette")
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("IdHistorique");

                    b.HasIndex("IdRecette");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("HISTORIQUE_CONSULTATION");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Ingredient", b =>
                {
                    b.Property<int>("IdIngredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ingredient");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngredient"));

                    b.Property<decimal?>("CoutUnitaire")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cout_unitaire");

                    b.Property<DateTime?>("DateMajPrix")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_maj_prix");

                    b.Property<bool>("Divisible")
                        .HasColumnType("bit")
                        .HasColumnName("divisible");

                    b.Property<bool>("EstAlcool")
                        .HasColumnType("bit")
                        .HasColumnName("est_alcool");

                    b.Property<bool>("EstAllergene")
                        .HasColumnType("bit")
                        .HasColumnName("est_allergene");

                    b.Property<bool>("EstVegan")
                        .HasColumnType("bit")
                        .HasColumnName("est_vegan");

                    b.Property<bool>("EstVege")
                        .HasColumnType("bit")
                        .HasColumnName("est_vege");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("UniteDefaut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unite_defaut");

                    b.HasKey("IdIngredient");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("INGREDIENT");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.MenuSoiree", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_menu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<decimal?>("CoutTotalEstime")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cout_total_estime");

                    b.Property<int?>("IdBoissonDessert")
                        .HasColumnType("int")
                        .HasColumnName("id_boisson_dessert");

                    b.Property<int?>("IdBoissonEntree")
                        .HasColumnType("int")
                        .HasColumnName("id_boisson_entree");

                    b.Property<int?>("IdBoissonPlat")
                        .HasColumnType("int")
                        .HasColumnName("id_boisson_plat");

                    b.Property<int?>("IdRecetteDessert")
                        .HasColumnType("int")
                        .HasColumnName("id_recette_dessert");

                    b.Property<int?>("IdRecetteEntree")
                        .HasColumnType("int")
                        .HasColumnName("id_recette_entree");

                    b.Property<int?>("IdRecettePlat")
                        .HasColumnType("int")
                        .HasColumnName("id_recette_plat");

                    b.Property<int>("IdSoiree")
                        .HasColumnType("int")
                        .HasColumnName("id_soiree");

                    b.Property<int?>("TempsTotalEstime")
                        .HasColumnType("int")
                        .HasColumnName("temps_total_estime");

                    b.HasKey("IdMenu");

                    b.HasIndex("IdBoissonDessert");

                    b.HasIndex("IdBoissonEntree");

                    b.HasIndex("IdBoissonPlat");

                    b.HasIndex("IdRecetteDessert");

                    b.HasIndex("IdRecetteEntree");

                    b.HasIndex("IdRecettePlat");

                    b.HasIndex("IdSoiree");

                    b.ToTable("MENU_SOIREE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.QuestionQuiz", b =>
                {
                    b.Property<int>("IdQuestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_question");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestion"));

                    b.Property<string>("Difficulte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("difficulte");

                    b.Property<string>("Explication")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explication");

                    b.Property<int?>("IdRecetteExemple")
                        .HasColumnType("int")
                        .HasColumnName("id_recette_exemple");

                    b.Property<string>("TexteQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("texte_question");

                    b.HasKey("IdQuestion");

                    b.HasIndex("IdRecetteExemple");

                    b.ToTable("QUESTION_QUIZ");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Recette", b =>
                {
                    b.Property<int>("IdRecette")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecette"));

                    b.Property<bool>("AdaptableVegan")
                        .HasColumnType("bit")
                        .HasColumnName("adaptable_vegan");

                    b.Property<bool>("AdaptableVege")
                        .HasColumnType("bit")
                        .HasColumnName("adaptable_vege");

                    b.Property<string>("AffiniteTannins")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("affinite_tannins");

                    b.Property<bool>("ContientFume")
                        .HasColumnType("bit")
                        .HasColumnName("contient_fume");

                    b.Property<bool>("ContientUmamiPur")
                        .HasColumnType("bit")
                        .HasColumnName("contient_umami_pur");

                    b.Property<decimal?>("CoutEstime")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cout_estime");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulte")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("difficulte");

                    b.Property<bool>("EstPubliee")
                        .HasColumnType("bit")
                        .HasColumnName("est_publiee");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int?>("IntensiteAromatique")
                        .HasColumnType("int")
                        .HasColumnName("intensite_aromatique");

                    b.Property<string>("ModeCuisson")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mode_cuisson");

                    b.Property<int?>("NiveauAcidite")
                        .HasColumnType("int")
                        .HasColumnName("niveau_acidite");

                    b.Property<int?>("NiveauAromeEpice")
                        .HasColumnType("int")
                        .HasColumnName("niveau_arome_epice");

                    b.Property<int?>("NiveauGras")
                        .HasColumnType("int")
                        .HasColumnName("niveau_gras");

                    b.Property<int?>("NiveauPiquant")
                        .HasColumnType("int")
                        .HasColumnName("niveau_piquant");

                    b.Property<int?>("NiveauSel")
                        .HasColumnType("int")
                        .HasColumnName("niveau_sel");

                    b.Property<int?>("NiveauSucre")
                        .HasColumnType("int")
                        .HasColumnName("niveau_sucre");

                    b.Property<int?>("NiveauUmami")
                        .HasColumnType("int")
                        .HasColumnName("niveau_umami");

                    b.Property<int?>("NombrePersonnesBase")
                        .HasColumnType("int")
                        .HasColumnName("nombre_personnes_base");

                    b.Property<bool>("PreparableAvance")
                        .HasColumnType("bit")
                        .HasColumnName("preparable_avance");

                    b.Property<int?>("TempsCuisson")
                        .HasColumnType("int")
                        .HasColumnName("temps_cuisson");

                    b.Property<int?>("TempsFinition")
                        .HasColumnType("int")
                        .HasColumnName("temps_finition");

                    b.Property<int?>("TempsPreparation")
                        .HasColumnType("int")
                        .HasColumnName("temps_preparation");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titre");

                    b.Property<string>("TypePlat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_plat");

                    b.Property<string>("TypeSauce")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_sauce");

                    b.HasKey("IdRecette");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("RECETTE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.RecetteFamilleAromatique", b =>
                {
                    b.Property<int>("IdRecette")
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    b.Property<int>("IdFamille")
                        .HasColumnType("int")
                        .HasColumnName("id_famille");

                    b.HasKey("IdRecette", "IdFamille");

                    b.HasIndex("IdFamille");

                    b.ToTable("RECETTE_FAMILLE_AROMATIQUE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.RecetteIngredient", b =>
                {
                    b.Property<int>("IdRecette")
                        .HasColumnType("int")
                        .HasColumnName("id_recette");

                    b.Property<int>("IdIngredient")
                        .HasColumnType("int")
                        .HasColumnName("id_ingredient");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantite");

                    b.HasKey("IdRecette", "IdIngredient");

                    b.HasIndex("IdIngredient");

                    b.ToTable("RECETTE_INGREDIENT");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.ReponseQuiz", b =>
                {
                    b.Property<int>("IdReponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reponse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReponse"));

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("bit")
                        .HasColumnName("est_correcte");

                    b.Property<int>("IdQuestion")
                        .HasColumnType("int")
                        .HasColumnName("id_question");

                    b.Property<string>("TexteReponse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("texte_reponse");

                    b.HasKey("IdReponse");

                    b.HasIndex("IdQuestion");

                    b.ToTable("REPONSE_QUIZ");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.ScoreQuiz", b =>
                {
                    b.Property<int>("IdScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_score");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdScore"));

                    b.Property<DateTime>("DateQuiz")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_quiz");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("niveau");

                    b.Property<int>("NombreQuestions")
                        .HasColumnType("int")
                        .HasColumnName("nombre_questions");

                    b.Property<int?>("ScoreObtenu")
                        .HasColumnType("int")
                        .HasColumnName("score_obtenu");

                    b.HasKey("IdScore");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("SCORE_QUIZ");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Soiree", b =>
                {
                    b.Property<int>("IdSoiree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_soiree");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSoiree"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<int?>("NombrePersonnes")
                        .HasColumnType("int")
                        .HasColumnName("nombre_personnes");

                    b.Property<int>("NombreVegans")
                        .HasColumnType("int")
                        .HasColumnName("nombre_vegans");

                    b.Property<int>("NombreVegetariens")
                        .HasColumnType("int")
                        .HasColumnName("nombre_vegetariens");

                    b.Property<string>("PreferenceAlcool")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("preference_alcool");

                    b.Property<int?>("TempsDisponible")
                        .HasColumnType("int")
                        .HasColumnName("temps_disponible");

                    b.Property<string>("TypeSoiree")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_soiree");

                    b.HasKey("IdSoiree");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("SOIREE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.SoireeContrainte", b =>
                {
                    b.Property<int>("IdSoiree")
                        .HasColumnType("int")
                        .HasColumnName("id_soiree");

                    b.Property<int>("IdContrainte")
                        .HasColumnType("int")
                        .HasColumnName("id_contrainte");

                    b.HasKey("IdSoiree", "IdContrainte");

                    b.HasIndex("IdContrainte");

                    b.ToTable("SOIREE_CONTRAINTE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.SubstitutionIngredient", b =>
                {
                    b.Property<int>("IdSubstitution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_substitution");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubstitution"));

                    b.Property<int>("IdIngredientOriginal")
                        .HasColumnType("int")
                        .HasColumnName("id_ingredient_original");

                    b.Property<int>("IdIngredientSubstitut")
                        .HasColumnType("int")
                        .HasColumnName("id_ingredient_substitut");

                    b.Property<string>("NoteCuisson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note_cuisson");

                    b.Property<decimal>("RatioConversion")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("ratio_conversion");

                    b.Property<string>("TypeSubstitution")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_substitution");

                    b.HasKey("IdSubstitution");

                    b.HasIndex("IdIngredientOriginal");

                    b.HasIndex("IdIngredientSubstitut");

                    b.ToTable("SUBSTITUTION_INGREDIENT");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("NiveauCuisine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("niveau_cuisine");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<bool>("PreferencesAlcool")
                        .HasColumnType("bit")
                        .HasColumnName("preferences_alcool");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("RegimeDefaut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("regime_defaut");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UTILISATEUR");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.UtilisateurContrainte", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("IdContrainte")
                        .HasColumnType("int")
                        .HasColumnName("id_contrainte");

                    b.HasKey("IdUtilisateur", "IdContrainte");

                    b.HasIndex("IdContrainte");

                    b.ToTable("UTILISATEUR_CONTRAINTE");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Accord", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Boisson", "Boisson")
                        .WithMany("Accords")
                        .HasForeignKey("IdBoisson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "Recette")
                        .WithMany("Accords")
                        .HasForeignKey("IdRecette")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boisson");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.BoissonFamilleAromatique", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Boisson", "Boisson")
                        .WithMany("FamillesAromatiques")
                        .HasForeignKey("IdBoisson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.FamilleAromatique", "Famille")
                        .WithMany("Boissons")
                        .HasForeignKey("IdFamille")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boisson");

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Etape", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "Recette")
                        .WithMany("Etapes")
                        .HasForeignKey("IdRecette")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Favori", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "Recette")
                        .WithMany("Favoris")
                        .HasForeignKey("IdRecette")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Utilisateur", "Utilisateur")
                        .WithMany("Favoris")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recette");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.HistoriqueConsultation", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "Recette")
                        .WithMany("Historiques")
                        .HasForeignKey("IdRecette")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Utilisateur", "Utilisateur")
                        .WithMany("Historique")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recette");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.MenuSoiree", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Boisson", "BoissonDessert")
                        .WithMany()
                        .HasForeignKey("IdBoissonDessert")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CulinaryPairing.Entities.Models.Boisson", "BoissonEntree")
                        .WithMany()
                        .HasForeignKey("IdBoissonEntree")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CulinaryPairing.Entities.Models.Boisson", "BoissonPlat")
                        .WithMany()
                        .HasForeignKey("IdBoissonPlat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "RecetteDessert")
                        .WithMany()
                        .HasForeignKey("IdRecetteDessert")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "RecetteEntree")
                        .WithMany()
                        .HasForeignKey("IdRecetteEntree")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "RecettePlat")
                        .WithMany()
                        .HasForeignKey("IdRecettePlat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CulinaryPairing.Entities.Models.Soiree", "Soiree")
                        .WithMany("Menus")
                        .HasForeignKey("IdSoiree")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoissonDessert");

                    b.Navigation("BoissonEntree");

                    b.Navigation("BoissonPlat");

                    b.Navigation("RecetteDessert");

                    b.Navigation("RecetteEntree");

                    b.Navigation("RecettePlat");

                    b.Navigation("Soiree");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.QuestionQuiz", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "RecetteExemple")
                        .WithMany()
                        .HasForeignKey("IdRecetteExemple")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RecetteExemple");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Recette", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Utilisateur", "Utilisateur")
                        .WithMany("RecettesCreees")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.RecetteFamilleAromatique", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.FamilleAromatique", "Famille")
                        .WithMany("Recettes")
                        .HasForeignKey("IdFamille")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "Recette")
                        .WithMany("FamillesAromatiques")
                        .HasForeignKey("IdRecette")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Famille");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.RecetteIngredient", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Ingredient", "Ingredient")
                        .WithMany("Recettes")
                        .HasForeignKey("IdIngredient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Recette", "Recette")
                        .WithMany("Ingredients")
                        .HasForeignKey("IdRecette")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.ReponseQuiz", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.QuestionQuiz", "Question")
                        .WithMany("Reponses")
                        .HasForeignKey("IdQuestion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.ScoreQuiz", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Utilisateur", "Utilisateur")
                        .WithMany("Scores")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Soiree", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Utilisateur", "Utilisateur")
                        .WithMany("Soirees")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.SoireeContrainte", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.ContrainteAlimentaire", "Contrainte")
                        .WithMany("Soirees")
                        .HasForeignKey("IdContrainte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Soiree", "Soiree")
                        .WithMany("Contraintes")
                        .HasForeignKey("IdSoiree")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrainte");

                    b.Navigation("Soiree");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.SubstitutionIngredient", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.Ingredient", "IngredientOriginal")
                        .WithMany("SubstitutionsOriginales")
                        .HasForeignKey("IdIngredientOriginal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Ingredient", "IngredientSubstitut")
                        .WithMany("SubstitutionsSubstituts")
                        .HasForeignKey("IdIngredientSubstitut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngredientOriginal");

                    b.Navigation("IngredientSubstitut");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.UtilisateurContrainte", b =>
                {
                    b.HasOne("CulinaryPairing.Entities.Models.ContrainteAlimentaire", "Contrainte")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdContrainte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinaryPairing.Entities.Models.Utilisateur", "Utilisateur")
                        .WithMany("Contraintes")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrainte");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Boisson", b =>
                {
                    b.Navigation("Accords");

                    b.Navigation("FamillesAromatiques");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.ContrainteAlimentaire", b =>
                {
                    b.Navigation("Soirees");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.FamilleAromatique", b =>
                {
                    b.Navigation("Boissons");

                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Ingredient", b =>
                {
                    b.Navigation("Recettes");

                    b.Navigation("SubstitutionsOriginales");

                    b.Navigation("SubstitutionsSubstituts");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.QuestionQuiz", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Recette", b =>
                {
                    b.Navigation("Accords");

                    b.Navigation("Etapes");

                    b.Navigation("FamillesAromatiques");

                    b.Navigation("Favoris");

                    b.Navigation("Historiques");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Soiree", b =>
                {
                    b.Navigation("Contraintes");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("CulinaryPairing.Entities.Models.Utilisateur", b =>
                {
                    b.Navigation("Contraintes");

                    b.Navigation("Favoris");

                    b.Navigation("Historique");

                    b.Navigation("RecettesCreees");

                    b.Navigation("Scores");

                    b.Navigation("Soirees");
                });
#pragma warning restore 612, 618
        }
    }
}
